### ISSUE TITLE
Creating Move-In Dates

### ISSUE THREAD

**Issue by gwenbeebe** [COHHIO/COHHIO_HMIS#81]
In the 00_get_export_and_ART script, the second condition in the code creating the MoveInDateAdjust column sets additional household members' move-in dates to their entry date if it doesn't match the head of household's entry date **and** they are in a housing program (line 267). 

Applying this logic to a hypothetical scenario where the head of household and another member have different program entry dates but have not moved into a unit yet seems like it could cause a false move-in date to be imputed to the non-head of household.

```
Enrollment <- Enrollment %>%
  left_join(small_project, by = "ProjectID") %>%
  left_join(HoHsEntry, by = "HouseholdID") %>%
  mutate(
    MoveInDateAdjust = case_when(
      EntryDate < mdy("10012017") &
        ProjectType %in% c(3, 9)
      ~ EntryDate,
      EntryDate != HoHsEntry &                        <- starting on this line
        ProjectType %in% c(3, 9, 13) ~ EntryDate,
      EntryDate >= mdy("10012017") &
        ProjectType %in% c(3, 9) &
        ymd(EntryDate) <= ymd(MoveInDate) &
        ymd(MoveInDate) <= ExitAdjust
      ~ MoveInDate,
      ymd(EntryDate) <= ymd(MoveInDate) &
        ymd(MoveInDate) <= ExitAdjust &
        ProjectType == 13 ~ MoveInDate
    ),
    EntryAdjust = case_when(
      ProjectType %in% c(1, 2, 4, 8, 12) ~ EntryDate,
      ProjectType %in% c(3, 9, 13) &
        !is.na(MoveInDateAdjust) ~ MoveInDateAdjust
    )
  )
```

**Comment by kiadso** [comment]
So if we added another condition that checks whether the HoH has a Move-In Date, would that answer this? Because I think that makes a lot of sense.

**Comment by gwenbeebe** [comment]
That could work...it could still move it too early, if the partner or child joined the entry a week after it was opened and they moved into their unit a couple months later. I don't know if it matters at that point or if I'm being too granular! But I think what I would do is run the MoveInDateAdjust for heads of household first, then change those lines to something like this pseudocode:

```
if entrydate <> hoh_entrydate and exists(hoh_moveindate):
     if entrydate >= hoh_moveindate
          then entrydate
     else hoh_moveindate
```

**Comment by gwenbeebe** [comment]
A couple examples of move-in dates being created by this that could be used for validating any changes: h_320104, h_333368, h_338026. Also h_299765, but that one is weird because the created move-in dates are earlier than the head of household's entry date (the head of household's entry date is not the household's earliest).

**Comment by kiadso** [comment]
I think I fixed this but I'm interested to hear your thoughts on how this all works. I changed this code all up so it's more concise and it even accounts for the h_299765 weirdness. Thanks so much for finding those examples- that was super helpful!!!

I'll be pushing edits soon.

**Comment by kiadso** [comment]
I'm going to leave this open in case the corrected logic (which I just pushed) is still off in some way! Thanks again for picking up on this.

**Comment by gwenbeebe** [comment]
I think we're really, really close. I think we still have a couple folks that should have move-in dates imputed from the head of household that aren't getting picked up, though (examples are 38677, 100038, 39311 & 39312).

What if...what if we did something like this:

- start with a column modification that leaves us with only the move-in dates we KNOW for each individual entry based on the export (keeps only move-in dates between entry and adjusted exit, adds move-in dates for those old housing projects, removes move-in dates for projects that shouldn't have them)
          - call it `known_move_in` for now

- find the earliest `known_move_in` in each household
          - call it `first_known_move_in` for now

- for any household members who 
          1) have no `known_move_in`
          2) AND are in a household that has a `first_known_move_in`,

     THEN set their move-in date to either their entry date or the household's `first_known_move_in`, whichever is later. 
     - (At first I had a third logical condition on that third step that looked at program type, but if we start by cleaning up the move-in dates in the first step then program is functionally checked by the second logical condition)
     

- If one or both conditions is not matched, keep whatever date or null value was already in the `known_move_in` column for that person

That would let us get around the potential issues with households like h_299765, households with no head of household marked, and the hypothetical ones with two heads of household who each have unique entry dates. We can impute move-in dates regardless of any head of household issues while keeping all the move-in dates that have been correctly entered.
